### ISSUE TITLE
Clarifications for Section 1

### ISSUE THREAD

**Issue by sophokles73** [thomas-fossati/draft-tls-cid#4]
Section 1:

I think we should mention that this extension is targeted at DTLS >=1.2 somewhere in the introduction.

> whereas the second provides a sequence of identifiers that are created using a HMAC-based OTP algorithm RFC4226 keyed with the session shared secret.

I assume that this is the session's *master secret*, isn't it? For me as a potential implementer, it would be beneficial if the spec were as precise as possible with such terms. If it is not really relevant whether it is the *master secret* or not, then we should also indicate this.

> The latter allows a client to shift to a new identifier, for example when switching networks, and is intended as a mechanism to counteract tracking.

Maybe we can add "tracking *by third party observers*" or something along these lines to make more explicit what should be prevented?

**Comment by thomas-fossati** [comment]
Hi Kai, thanks.  Commit 18ea659 should address all your points above.

Re: s/shared/master/. It wouldn't be 100% correct to say that, because it's not the master itself that is used but a key derived from the master.  So I have slightly changed the text and pointed to the section where the exact exporting mechanism is described.

**Comment by sophokles73** [comment]
Hi Thomas,

thanks for the quick response. I have briefly gone over RFC 4226 (HOTP) and RFC 5705 (Exporters). The former explicitly mentions SHA-1 as the hash function being used for creating the 20 byte input for the OTP generator while the latter re-uses the TLS defined PRF which, for cipher suites defined by TLS >= 1.2, SHOULD be SHA-256. I think it would be worth mentioning which one we intend to use for the generation of the OTPs (I'm assuming SHA-256).

**Comment by thomas-fossati** [comment]
Kai, although I don't see any technical problem moving HOTP to SHA-256. However, I don't think this is strictly needed from a security perspective (see https://tools.ietf.org/html/rfc4226#appendix-B.2) and it'd also be a bit tricky to reference RFC 4226 as normative but at the same time updating it.

(BTW, do you think the original issue is closed?)

**Comment by sophokles73** [comment]
My concern is more that we need to implement a second PRF function in order to support it. We already have a SHA-256 based PRF because we implement TLS 1.2. Now we need to implement a second (weaker) PRF because we refer to an (older) RFC ...

And yes, the original issue is closed :-)

**Comment by sophokles73** [comment]
I have checked how we implemented this in Californium. Looks like we are simply using the JRE's standard HmacSHA256 algorithm implementation. There also is an implementation of HmacSHA1 available so this shouldn't be a big issue ...

**Comment by thomas-fossati** [comment]
Excellent.
